{
 "title": "Windows",
 "description": "Windows monitoring Dashboard.\r\n\r\n(Translated StarsL.cn's work. ID: 10467)",
 "tags": [
  "Prometheus",
  "windows",
  "windows_exporter"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(windows_os_hostname, job)"
   },
   {
    "name": "hostname",
    "label": "hostname",
    "query": "label_values(windows_os_hostname{job=~\"$job\"}, hostname)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(windows_os_hostname{job=~\"$job\",hostname=~\"$hostname\"}, instance)"
   },
   {
    "name": "show_hostname",
    "label": "show_hostname",
    "query": "label_values(windows_os_hostname{job=~\"$job\",instance=~\"$instance\"}, hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Resource overview. Currently selected host:【$show_hostname】 Instance: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$job:Overview of Server Resources",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "windows_os_info{job=~\"$job\"} * on(instance) group_right(product) windows_os_hostname"
    },
    {
     "expr": "(time() - windows_system_boot_time_timestamp{job=~\"$job\"})"
    },
    {
     "expr": "count(count by (core) (windows_cpu_time_total{job=~\"$job\"})) - 0"
    },
    {
     "expr": "avg by (instance) (windows_cpu_core_frequency_mhz{job=~\"$job\"})"
    },
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{job=~\"$job\",mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "CPU Utilization"
    },
    {
     "expr": "windows_memory_physical_total_bytes{job=~\"$job\"} - 0"
    },
    {
     "expr": "100 - 100 * windows_memory_available_bytes{job=~\"$job\"} / windows_memory_physical_total_bytes{job=~\"$job\"}",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "1 - (windows_logical_disk_free_bytes{job=~\"$job\",volume=~\"C:\"}/windows_logical_disk_size_bytes{job=~\"$job\",volume=~\"C:\"})"
    },
    {
     "expr": "max by (instance) (1-windows_logical_disk_free_bytes{job=~\"$job\"}/windows_logical_disk_size_bytes{job=~\"$job\"})"
    },
    {
     "expr": "windows_system_processes{job=~\"$job\"}"
    },
    {
     "expr": "sum by (instance) (windows_service_state{job=~\"$job\",state=~\"running\"})"
    }
   ]
  },
  {
   "title": "CPU Usage by Host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{job=~\"$job\",mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100 * windows_memory_available_bytes{job=~\"$job\"} / windows_memory_physical_total_bytes{job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network details of the maximum traffic network card of each host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "bps", "label": "Download & Upload" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "max by (instance) (irate(windows_net_bytes_sent_total{job=~\"$job\",nic!~'isatap.*|VPN.*'}[2m]))*8",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_上传",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "-max by (instance) (irate(windows_net_bytes_received_total{job=~\"$job\",nic!~'isatap.*|VPN.*'}[2m]))*8",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_Download",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Maximum disk read/write details for each host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 7 },
   "yaxes": [
    { "format": "Bps", "label": "Read & Write" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "-max by (instance) (irate(windows_logical_disk_read_bytes_total[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_Read",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "max by (instance) (irate(windows_logical_disk_write_bytes_total[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_Writing",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Maximum Disk IO by Host Details",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "yaxes": [
    { "format": "iops", "label": "Read & Write" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "-max by (instance) (irate(windows_logical_disk_reads_total[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_Read",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "max by (instance) (irate(windows_logical_disk_writes_total[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_Writing",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Details of resources 【$show_hostname：$instance】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Start-up time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 14 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(time() - windows_system_boot_time_timestamp{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(windows_cpu_time_total{job=~\"$job\",instance=~\"$instance\",mode=\"idle\"}[2m])))*100"
    }
   ]
  },
  {
   "title": "Utilization by sector",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (windows_logical_disk_free_bytes{job=~\"$job\",instance=~\"$instance\"} / windows_logical_disk_size_bytes{job=~\"$job\",instance=~\"$instance\"})*100",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(windows_service_state{job=~\"$job\",instance=~\"$instance\"}) by (state)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{state}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Number of processes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "windows_system_processes{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Number of processes"
    }
   ]
  },
  {
   "title": "Number of CPU cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 16 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (core) (windows_cpu_time_total{job=~\"$job\",instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (windows_memory_available_bytes{job=~\"$job\",instance=~\"$instance\"} / windows_memory_physical_total_bytes{job=~\"$job\",instance=~\"$instance\"})*100"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 18 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "windows_memory_physical_total_bytes{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - avg(irate(windows_cpu_time_total{job=~\"$job\",instance=~\"$instance\",mode=\"idle\"}[5m]))*100",
     "legendFormat": "CPU Utilization"
    }
   ]
  },
  {
   "title": "Memory Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_memory_physical_total_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Total Physical Memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_memory_available_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Remaining Physical Memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_memory_commit_limit{job=~\"$job\",instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Virtual memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "(windows_memory_commit_limit{job=~\"$job\",instance=~\"$instance\"} - windows_memory_committed_bytes{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "Free virtual memory"
    }
   ]
  },
  {
   "title": "Remaining Disk Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_logical_disk_free_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Residual Space {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_logical_disk_size_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Total Space {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Network Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_bytes_sent_total{job=~\"$job\",instance=~\"$instance\",nic!~'isatap.*|VPN.*'}[5m])*8>0\r",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{nic}}-Sent-Upload",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_bytes_received_total{job=~\"$job\",instance=~\"$instance\",nic!~'isatap.*|VPN.*'}[5m])*8\n",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{nic}}-Received-Download",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Disk Read/Write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_read_bytes_total{job=~\"$job\",instance=~\"$instance\"}[5m])\r",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "read {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_write_bytes_total{job=~\"$job\",instance=~\"$instance\"}[5m])\r",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "write {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_reads_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "read {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_writes_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "write {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(irate(windows_net_bytes_total{job=~\"$job\",instance=~\"$instance\",nic!~'isatap.*|VPN.*'}[5m]) * 8 / windows_net_current_bandwidth_bytes{job=~\"$job\",instance=~\"$instance\",nic!~'isatap.*|VPN.*'}) * 100",
     "legendFormat": "{{nic}}"
    }
   ]
  },
  {
   "title": "Network discarded/error packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_packets_outbound_discarded_total{job=~\"$job\",instance=~\"$instance\", nic!~'isatap.*|VPN.*'}[5m]) + irate(windows_net_packets_outbound_errors_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "outbound",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_packets_received_discarded_total{job=~\"$job\",instance=~\"$instance\", nic!~'isatap.*|VPN.*'}[5m]) + irate(windows_net_packets_received_errors_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "received",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "system_threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_system_threads{job=~\"$job\",instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "system_threads",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Exception dispatches/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_system_exception_dispatches_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "exceptions",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "NVIDIA GPU", "type": "row", "gridPos": { "x": 0, "y": 42, "w": 24, "h": 1 } },
  {
   "title": "GPU Temperature",
   "type": "stat",
   "gridPos": { "x": 0, "y": 43, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_temperature_gpu{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "stat",
   "gridPos": { "x": 4, "y": 43, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio{instance=~\"$instance\"} * 100"
    }
   ]
  },
  {
   "title": "Power Draw",
   "type": "stat",
   "gridPos": { "x": 8, "y": 43, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_power_draw_watts{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "stat",
   "gridPos": { "x": 12, "y": 43, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_fan_speed_ratio{instance=~\"$instance\"} * 100"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "x": 16, "y": 43, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_memory_used_bytes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory Used %",
   "type": "stat",
   "gridPos": { "x": 20, "y": 43, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(nvidia_smi_memory_used_bytes{instance=~\"$instance\"} / nvidia_smi_memory_total_bytes{instance=~\"$instance\"}) * 100"
    }
   ]
  },
  {
   "title": "Temperature over time",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 47, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "nvidia_smi_temperature_gpu{instance=~\"$instance\"}",
     "legendFormat": "GPU temp"
    }
   ]
  },
  {
   "title": "Utilization over time",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 47, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio{instance=~\"$instance\"} * 100",
     "legendFormat": "GPU"
    },
    {
     "expr": "nvidia_smi_utilization_memory_ratio{instance=~\"$instance\"} * 100",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Power draw",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 55, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "nvidia_smi_power_draw_watts{instance=~\"$instance\"}",
     "legendFormat": "Power"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 55, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nvidia_smi_memory_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "nvidia_smi_memory_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Hardware Sensors (LibreHardwareMonitor)",
   "type": "row",
   "gridPos": { "x": 0, "y": 63, "w": 24, "h": 1 }
  },
  {
   "title": "CPU Package Temp",
   "type": "stat",
   "gridPos": { "x": 0, "y": 64, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ohm_cpu_temperature{instance=~\"$instance\",name=~\"Core.*Tctl.*|Core.*Tdie.*|Package\"})"
    }
   ]
  },
  {
   "title": "Motherboard Temp",
   "type": "stat",
   "gridPos": { "x": 4, "y": 64, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_superio_temperature{instance=~\"$instance\", name=\"Motherboard\"}"
    }
   ]
  },
  {
   "title": "CPU Power",
   "type": "stat",
   "gridPos": { "x": 8, "y": 64, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ohm_cpu_power{instance=~\"$instance\", name=\"Package\"})"
    }
   ]
  },
  {
   "title": "Hottest NVMe",
   "type": "stat",
   "gridPos": { "x": 12, "y": 64, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ohm_storage_temperature{instance=~\"$instance\", name=\"Temperature\"})"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "stat",
   "gridPos": { "x": 16, "y": 64, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ohm_cpu_load{instance=~\"$instance\", name=\"CPU Total\"})"
    }
   ]
  },
  {
   "title": "Memory Load",
   "type": "stat",
   "gridPos": { "x": 20, "y": 64, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_memory_load{instance=~\"$instance\", name=\"Memory\"}"
    }
   ]
  },
  {
   "title": "CPU temperatures (all sensors)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 68, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ohm_cpu_temperature{instance=~\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Storage temperatures",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 68, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ohm_storage_temperature{instance=~\"$instance\"}",
     "legendFormat": "{{hw}} {{name}}"
    }
   ]
  },
  {
   "title": "Fan speeds",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 76, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "targets": [
    {
     "expr": "ohm_superio_fan{instance=~\"$instance\"} > 0",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "ohm_gpunvidia_fan{instance=~\"$instance\"}",
     "legendFormat": "GPU {{name}}"
    }
   ]
  },
  {
   "title": "CPU power & motherboard temps",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 76, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ohm_cpu_power{instance=~\"$instance\"}",
     "legendFormat": "CPU {{name}} (W)"
    },
    {
     "expr": "ohm_superio_temperature{instance=~\"$instance\"}",
     "legendFormat": "Mobo {{name}} (°C)"
    }
   ]
  }
 ]
}